### ISSUE TITLE
mof replays are 1-indexed

### ISSUE THREAD

**Issue by n-rook** [n-rook/thscoreboard#181]
I added

```
    def testStages(self):
        r = ParseTestReplay('th10_normal')
        self.assertEqual(r.stages[0].stage, 0)
```

to test_replay_parsing.py and it failed.

They should be 0-indexed, since the field is documented as 0-indexed (and some other code will probably expect it)

**Comment by 32th-System** [comment]
All games from th10 onwards store their internal stage number, as well as the stage number in the replay 1 indexed and the replay parsing code just copies the stage number 1 to 1. Should all stage numbers be 1 or 0 indexed?

**Comment by n-rook** [comment]
Hmm, that's a good point. Maybe it's not strictly a bug then. I do think they should all be 0 indexed. (Or they should all be 1 indexed! But I think it'd be best for it to be consistent, since of course users won't care about the difference.)

**Comment by raviddog** [comment]
game_fields.py already has a function that corrects the displayed stage, required because of IN's A and B stages, so there's no way of working around that.

But if we want to 0-index them by default for model consistency that's fine by me. Either do that or edit the field description in the model to mention that they're not consistent because ZUN isn't consistent and to add a correction to game_fields.py

**Comment by n-rook** [comment]
I think I overreacted a little because I was surprised my "stage 2" variables in a test I wrote were actually stage 1. I do still think this would be a good idea though

**Comment by raviddog** [comment]
Apologies for coming back to this suddenly, but I've thought about it a bit and I think the stage field should be 1 indexed. The array itself is already 0 indexed so making this stage field follow it serves no purpose, and now we have a lot of stage-num subtracting and adding in the code that ultimately results in things like `stage2 = (stage = 1)`
I hadn't fully decided earlier on since we were working on the earlier games that don't explicitly state which stage the split is for, but all modern games do include that field and ZUN seems to be consistent on this part now.
