### ISSUE TITLE
clicking the email registration confirmation link shouldn't require another confirmation on the page

### ISSUE THREAD

**Issue by raviddog** [n-rook/thscoreboard#33]

**Comment by n-rook** [comment]
This is actually kind of complicated: the problem is that modifying state with a GET is illegal in HTTP. Obviously this does not mean the Internet police will arrest us, but there have been cases before of things like malware scanners or cache services visiting links in emails.

I think it is possible to work around this but we would have to use JavaScript to do it, so I have not bothered yet.

**Comment by 32th-System** [comment]
It also shouldn't require you to log in again separately

**Comment by n-rook** [comment]
That one… is not complicated

**Comment by raviddog** [comment]
not complicated, but still useful to leave it here as a reminder

**Comment by raviddog** [comment]
y'know what, good enough
